author: MDCollins
database: false
description: Wrote my own jail plugin because the others either sucked or required
  too much set up.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.blockmovers.plugins.simplejailr.SimpleJailr
name: SimpleJailr
startup: postworld
url: http://blockmovers.com/
version: '0.2'
commands:
  jail:
    usage: /<command> <action>
    description: SimpleJailr root command
permissions:
  simplejailr.unjailable:
    default: false
    description: Cannot be thrown in jail
  simplejailr.jailor:
    default: false
    description: Can jail/unjail people
  simplejailr.admin:
    default: false
    description: Can set the jail point and unjail command